tinyMCE continued
The dialog now opens, but doesn't function.  There isn't an infinite scroll for selecting terms cleanly --- read-only textbox looking thing instead of a dropdown for the "Select term" might look better?  More substantively, I see the following console errors:

Uncaught Error: Errors:
Failed path: (data)
Could not find valid *required* value for "term_id" in {
  "term_query": "",
  "text": ""
}
Failed path: (data)
Could not find valid *required* value for "domain_id" in {
  "term_query": "",
  "text": ""
}

Input object: {
  "term_query": "",
  "text": ""
}
    at theme.min.js:1:31469
    at Object.fold (theme.min.js:1:6460)
    at Tr (theme.min.js:1:31453)
    at theme.min.js:1:426216
    at A.map (theme.min.js:1:1129)
    at theme.min.js:1:426208
    at theme.min.js:1:426261
    at n (theme.min.js:1:425958)
    at Object.setData (theme.min.js:1:426112)
    at theme.min.js:1:434653
(anonymous)	@	theme.min.js:1
fold	@	theme.min.js:1
Tr	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
map	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
n	@	theme.min.js:1
setData	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
open	@	theme.min.js:1
r	@	theme.min.js:1
open	@	theme.min.js:1
(anonymous)	@	tinymce.min.js:11
s	@	tinymce.min.js:11
open	@	tinymce.min.js:11
onAction	@	definition-form.component.ts:119
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
V	@	theme.min.js:1
run	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
fold	@	theme.min.js:1
xv	@	theme.min.js:1
yv	@	theme.min.js:1
wv	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
li	@	theme.min.js:1
triggerEvent	@	theme.min.js:1
Lc	@	theme.min.js:1
Fc	@	theme.min.js:1
Nc	@	theme.min.js:1
e	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
fold	@	theme.min.js:1
xv	@	theme.min.js:1
yv	@	theme.min.js:1
wv	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
li	@	theme.min.js:1
triggerEvent	@	theme.min.js:1
(anonymous)	@	theme.min.js:1
(anonymous)	@	theme.min.js:1

zone.js:163 Uncaught TypeError: api.getForm is not a function
    at Object.next (definition-form.component.ts:159:44)
﻿